version: '3'
services:
  dev:
    image: watchdogs39/watchdogs-dev
    container_name: watchdogs-dev
    ports:
      - '5173:5173'
    networks:
      - watchdogs-network
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - redis-db
    command: npm run dev-all
  
  redis-db: 
    image: watchdogs39/watchdogs-redis
    container_name: watchdogs-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - prod-redis-volume:/var/lib/redis/data
    ports:
      - 6379:6379
    networks:
      - watchdogs-network
    command: redis-server
volumes:
  node_modules:
  prod-redis-volume:
  
networks:
  watchdogs-network: